[package]
name = "fixed_torus"
version = "0.1.0"
edition = "2021"

[dependencies]
statrs = { version = "0.16.0", optional = true }
rand = { version = "0.8.5", optional = true }

[dev-dependencies]
approx = "0.5.1"

[features]
random = ["dep:statrs", "dep:rand"]

default = ["random"]
